# Generated by Django 4.2.11 on 2024-04-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_bookmarks_alter_post_category_and_more'),
    ]

    operations = [
    ]
