# Generated by Django 4.2.11 on 2024-04-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_featured_image_post_post_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
    ]
